name: Slides

on:
  push:
    branches:
      - master
      - main
      - publish_pdfs
  pull_request:
    branches:
      - master
      - main

jobs:
  slides:
    name: slides
    runs-on: ubuntu-latest
    steps:
      - name:
        shell: bash
        run: |
          mkdir mock-slides
          echo "this is the content" > mock-slides/test.txt

      - name: Publish slides on GitHub Pages
        if: github.ref_name == 'publish_pdfs'
        shell: bash
        run: echo "It works on ${{github.ref_name}}"

      - name: Publish artifact with mock-slides
        if: github.ref_name == 'publish_pdfs'
        uses: actions/upload-pages-artifact@v2
        with:
          path: "mock-slides/"

  # Deploy job
  deploy:
    needs: slides

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 # or the latest "vX.X.X" version tag for this action 
        with:
          artifact_name: 'github-pages'
