name: Slides

on:
  push:
    branches:
      - master
      - main
      - publish_pdfs
  pull_request:
    branches:
      - master
      - main
      - publish_pdfs

jobs:
  slides:
    name: slides
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: seanmiddleditch/gha-setup-ninja@v3

    - name: Install dependencies
      shell: bash
      run: |
        sudo apt update
        sudo apt install chromium-browser
        wget https://github.com/marp-team/marp-cli/releases/download/v3.2.1/marp-cli-v3.2.1-linux.tar.gz
        tar -xf ./marp-cli-v3.2.1-linux.tar.gz
        sudo ln -s $(pwd)/marp /usr/bin/marp

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: |
        cmake -S $GITHUB_WORKSPACE -B . -DCMAKE_BUILD_TYPE=Debug

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config Debug

    - name: Copy slides
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: |
        mkdir slides
        # For the moment we just PDF slides, because HTML have problem with images urls
        cp ./*.pdf ./slides/

    - name: Archive slides
      uses: actions/upload-artifact@v3
      with:
        name: slides
        path: ${{runner.workspace}}/build/slides

  deploy:
    if: github.ref_name == 'publish_pdfs' # TODO change this to `main` before merging
    needs: slides

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
    - name: Download slides
      uses: actions/download-artifact@v3
      with:
        name: slides

    - name: Generate GitHub Pages index
      shell: bash
      run: |
        echo "<h1>Slides from the CSCS Advanced C++ Course 2023</h1>" >> index.html
        echo "<ul>" >> index.html
        find . -name "*.pdf" -exec echo "<li><a href='{}'>{}</a></li>" \; | sort >> index.html
        echo "</ul>" >> index.html

    - name: Publish artifact with slides to GitHub Pages
      uses: actions/upload-pages-artifact@v2
      with:
        path: .

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
      with:
        artifact_name: 'github-pages'
